apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  labels:
    name: portfolio-service
    app: portfolio-app
  namespace: _{_NAMESPACE_}_
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
      protocol: TCP
  selector:
    name: portfolio-pod
    app: portfolio-app